[package]
name = "fixed"
version = "1.3.0"
cairo-version = ">=2.8.0"
edition = "2023_10"
description = "Math library in Cairo using a fixed point representation"
homepage = "https://github.com/bengineer42/cubit"

[lib]

[dependencies]
starknet = ">=2.8.0"

[dev-dependencies]
cairo_test = "2.8.4"
